### ISSUE TITLE
Logo ideas

### ISSUE THREAD

**Issue by lwjohnst86** [au-oc/admin#15]
Image ideas:

- https://fontawesome.com/icons/user-friends?style=solid
- https://fontawesome.com/icons/user?style=solid
- https://www.istockphoto.com/dk/vector/group-of-people-population-icon-gm844156918-138139885
- https://fontawesome.com/icons/laptop-code?style=solid

Background with light code text? And AU CRU wording across top.

**Comment by lwjohnst86** [comment]
Two logos? One "hex"/circular and another longer style for header of website?

**Comment by SaraTomiolo** [comment]
![logoCRU2](https://user-images.githubusercontent.com/47562026/66938106-e14cf100-f040-11e9-8c3d-6dba5c49ffec.png)

OR 

![logoCRU1](https://user-images.githubusercontent.com/47562026/66938109-e4e07800-f040-11e9-82d4-1f573172422b.png)


What do you think of these two? Any suggestion?

**Comment by izabelcavassim** [comment]
I liked the second the most :)

**Comment by adivea** [comment]
I like the first one for its simplicity and symbolism of building blocks. :)

**Comment by lwjohnst86** [comment]
I just realized, the first logo is a bit similar to the Windows logo: https://arstechnica.com/information-technology/2012/08/microsoft-unveils-a-boxy-new-windows-inspired-logo-2/

We should probably change it up a bit, like the colours or something, to distinguish from Windows.

**Comment by SaraTomiolo** [comment]
![logoCRU2_b](https://user-images.githubusercontent.com/47562026/69337086-52934b80-0c60-11ea-84f2-f96064db3ea6.png)

how about this?

**Comment by adivea** [comment]
Hah, conditioning by Microsoft revealed! ;) I am very happy with new colors.

**Comment by SaraTomiolo** [comment]
ehehhe... the bias we don't know we have... sneaky!

**Comment by lwjohnst86** [comment]
Hmm, not a huge fan of the purple and green colours (as a colour blind person). What about having the colours of the [Git logo](https://git-scm.com/downloads/logos), the [R logo](https://www.r-project.org/logo/Rlogo.png), and the [Python logo](https://www.python.org/static/community_logos/python-logo-master-v3-TM.png)? 

Looking at the [Bash logo](https://github.com/odb/official-bash-logo/blob/master/assets/Logos/Identity/PNG/BASH_logo-transparent-bg-bw.png), the shape is similar to one of the designs we were thinking about before... Maybe make a logo of the colours of Git, R, and Python, in a Bash type shape? Just to see how it looks like.

**Comment by lwjohnst86** [comment]
The yellow above already is like the Python logo, so no need to change that. But maybe the others?

**Comment by SaraTomiolo** [comment]
mmmh not convinced about the Bash logo idea. I think that the strength of this logo is the simplicity and the idea of building blocks (and Lego...)
As to the colors you suggested, I can try, but then we will be close to windows ones again.

**Comment by lwjohnst86** [comment]
Yea, I'm not a huge fan of the bash shape either.. just thinking it would be nice to incorporate the four main "tools" being taught... but not necessary! I also like the simplicity of the present one.

Yea, I know we'll be close the windows... but :man_shrugging: at least we have a rationale for why we chose the colours we did, maybe that would be good enough? Then again, Windows doesn't have a monopoly on the colours since, as you say, they also look like Lego blocks.

**Comment by SaraTomiolo** [comment]
But are we teaching bash and shell? And do we need to have a reason for choosing colors other than they are pretty and eye catching? :)

**Comment by lwjohnst86** [comment]
We might teach bash and shell.. .they are definitely covered in the SWC/DC workshops!

And its true, we don't need a reason for the colours. :)

**Comment by SaraTomiolo** [comment]
![logo_options](https://user-images.githubusercontent.com/47562026/69478442-a2a21780-0df2-11ea-8b0a-8cf1704a1c18.png)

**Comment by SaraTomiolo** [comment]
Choose one of the options: A,B,C, or D :)

**Comment by lwjohnst86** [comment]
I think I like A best.

**Comment by adivea** [comment]
I like either B or D (mostly because I can read them more easily:)

**Comment by lwjohnst86** [comment]
Alright, let's do B then! Thanks :grin:
