### ISSUE TITLE
Potential schedule of events over next many months

### ISSUE THREAD

**Issue by lwjohnst86** [au-oc/admin#19]
Either as a list here or a share-able (but only commentable) link to a Google Sheet.

Maybe for now do for the next 6 months?

**Comment by SaraTomiolo** [comment]
I have tried to organize the requests of topics to learn in blocks and created a very tentative schedule stretching over the next 7 months. I have left out for the time being topics related to statistics... here is a link to the google spreadsheet file 
https://docs.google.com/spreadsheets/d/1cxzEiejlEXfODZpmaEbJv4UF9iGuPtGfhzlDfeR2yCQ/edit?ts=5d9dc7e6#gid=181649958

**Comment by lwjohnst86** [comment]
Potential schedule is [here](https://docs.google.com/spreadsheets/d/15QptbsH4z1efB_LFG6vTq631iy_lUoQccdYWVm389QU/edit?usp=sharing) and has an instructor signup column.
