### ISSUE TITLE
Create a mailing list for people to subscribe to

### ISSUE THREAD

**Issue by lwjohnst86** [au-oc/admin#8]

**Comment by lwjohnst86** [comment]
Maybe use AU services as described [here](https://medarbejdere.au.dk/en/administration/it/email-and-calendar/mailing-lists/mailman-mailing-list/). For this we'd need at least:

- One or more list administrators/owners who are responsible for maintaining the list and deciding who gets to send emails through the list.
- One or more list members, who are allowed to send emails through to the list.

**Comment by lwjohnst86** [comment]
Maybe have two mailing lists, one for R and one for Python?

(Edit: Actually, easier just to have one)

**Comment by lwjohnst86** [comment]
@adivea or @danm0nster to have an AU mailing list, we need a staff member to administrate the list and give out access, etc. Have either of you (or someone else you know) set up something like this before?

By Dec I may not be considered "staff" depending on how my contract can be settled (I'm moving to an institute up at Skejby, but still affiliated with AU). I'll message IT support and see if I can set up a mailing list, if I can't I'll post an update and we can figure it from there.

**Comment by danm0nster** [comment]
@lwjohnst86, I already have a mailman mailing list for associated researchers at Cognition and Behavior Lab, and wouldn't mind administrating another one. What is the purpose of the mailing list? Announcements, or discussions? Also what would be the policy for subscribing (open to all, or only AU employees and affiliated persons)? If it's mainly announcements, it might be better to use another tool, but if all members should be able to post, then mailman is fine.

**Comment by lwjohnst86** [comment]
Its almost entirely for announcements. Ok, that makes things simpler than. Which other tool would you recommend? I've used googlegroups before for sending out emails, is that something you'd recommend or something else?

**Comment by danm0nster** [comment]
I think Campaign Monitor is a nice tool. We have access through AU/Typo3, and it's used for newsletters all over AU. It's quite easy to set up a template and send out nicely formatted e-mails with images etc. It is also easy for people to sign-up to receive the announcements.

*But* it cannot be used for discussions like a mailing list.

**Comment by lwjohnst86** [comment]
Done. Using TinyLetter https://tinyletter.com/ .. it's very simple and has exactly the features I am looking for (and no more).
